### ISSUE TITLE
HEAD support

### ISSUE THREAD

**Issue by hcarty** [andersfugmann/aws-s3#1]
Useful for, among other things, checking the size of an object in S3.

**Comment by hcarty** [comment]
I may be able to put in a PR for this but I wanted to record the request formally.

**Comment by andersfugmann** [comment]
I think is makes sense to implement HEAD support. In the meantime you could do an LS to get the size, storage class, last modified and etag.

**Comment by hcarty** [comment]
Thanks - that's what I've been using as a work-around and it's been fine, at least for my current loads which don't need to make many HEAD requests.

**Comment by hcarty** [comment]
Thank you!
