### ISSUE TITLE
Support for other S3-compatible services

### ISSUE THREAD

**Issue by hcarty** [andersfugmann/aws-s3#10]
This would be useful for things like [minio](https://www.minio.io/) for local development/testing and the many S3-compatible service providers out there.

**Comment by andersfugmann** [comment]
Great. Thanks for the pointer. I will look into this soon - Maybe this could even be used for this library for automated integration tests though travis.

My idea would be to overload region to be something like 
`Vendor of region_name * host * port`, and possibly a
`val minio: host -> port -> Region.t` helper function. 

(The region name is used when creating signatures, so it needs to be know somehow).

**Comment by hcarty** [comment]
Closing now that #12 is merged.
