### ISSUE TITLE
Pre-signed URLs

### ISSUE THREAD

**Issue by hcarty** [andersfugmann/aws-s3#17]
It would be nice to support generating pre-signed URLs for ephemeral GET and PUT operations.

**Comment by andersfugmann** [comment]
Interesting idea. 

Currently the signing uses HTTP Authorization header and not get parameters, but I guess its fairly easy to create query parameters also. 

How would you construct PUT presigned url's? You would need to supply the SHA + content length then? And If I read the documentation correctly, PUT request also needs special headers which are used when signing.

**Comment by hcarty** [comment]
I think these are the docs describing how to actually create pre-signed URLs.  https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth

If you don't have time to work on this I may be able to spend some time on it next week.

**Comment by andersfugmann** [comment]
Merged - Thanks. New version on its way into opam-repository: https://github.com/ocaml/opam-repository/pull/13570
