### ISSUE TITLE
make a new opam release to lift the restriction on lwt version

### ISSUE THREAD

**Issue by tatchi** [andersfugmann/aws-s3#36]
There is currently an upper bound on `lwt` in the latest `4.8.0` version released to opam: https://github.com/ocaml/opam-repository/blob/master/packages/aws-s3-lwt/aws-s3-lwt.4.8.0/opam#L16

It seems that master should now work fine with the latest `lwt` (see https://github.com/andersfugmann/aws-s3/issues/35).

It would be nice to release a new version based on master to remove the current restriction on the `lwt` version.

**Comment by andersfugmann** [comment]
On its way: https://github.com/ocaml/opam-repository/pull/25497

**Comment by tatchi** [comment]
Thanks @andersfugmann 🤗
