### ISSUE TITLE
Streaming upload/download support

### ISSUE THREAD

**Issue by hcarty** [andersfugmann/aws-s3#4]
This can be important under high concurrency conditions and when the files/data being worked with are large.  It may not be feasible to hold the content in a `string` all at once.

**Comment by hcarty** [comment]
I can put some effort into implementing this but it would be a somewhat invasive change.  The code as it currently exists takes advantage of the fact that it has the data in-hand to get size and hash information.

Would it be acceptable to break the API to add streaming support?  My initial idea is to use the cohttp-backend-specific body type rather than a string for the `PUT` request body and `GET` response body.

`GET` would be a relatively small change to the code.

`PUT` would be more invasive.  It requires changing how content length and hash headers are added.  If a stream value is used (`` `Stream _ `` for Lwt, `` `Pipe _ `` for Async) then the content length and SHA256 headers could be left out of the request.  The MD5 could be calculated as the data stream through then compared against the etag response from S3.  Or the hash calculation and comparison against the etag response could be left up to the caller.

**Comment by andersfugmann** [comment]
That would be great. A PR is more that welcome. 

The content-length header is required for put operations, but I think its reasonable to require the user to know the length of the data to be uploaded. 
 
As for the breaking change, If we can have a streaming interface, it should be trivial to have the existing interface use that. The only difference I see is that the result of an put operation might yield "invalid_checksum", but I would consider that a minor change.

**Comment by hcarty** [comment]
> The content-length header is required for put operations, but I think its reasonable to require the user to know the length of the data to be uploaded.

Agreed.  I'll make the stream length a required argument.

> As for the breaking change, If we can have a streaming interface, it should be trivial to have the existing interface use that. The only difference I see is that the result of an put operation might yield "invalid_checksum", but I would consider that a minor change.

I was thinking of changing the existing function interfaces, but having `*_streaming` equivalents makes more sense from a limiting breakage perspective!  And it keeps the simple case (I have the whole payload in-hand) simple.

I'll try to get time for a PR in the new few days.

**Comment by andersfugmann** [comment]
Status update: I've been working on getting chunked uploads working, and it seems working now where each chunk is signed. I have, however, discovered that Cohttp will convert a stream of string into a single string (draining the input), so all work is in vain, unless we switch away from CoHttp. 

Its not a lot of work, so This is the next thing I will work on. Most pieces are in place already, so I'm not too discouraged by this.

**Comment by andersfugmann** [comment]
@hcarty I'd like to hear commented on the suggested API in #8. 
Most notably is the new pipe module I implemented which is based on the API of Async.Pipe.

We need a pipe which can be closed from the receiving end  (i.e. Pipe.close reader), to allow consumers to indicate that no more data is needed, and the http connection can be closed.

**Comment by andersfugmann** [comment]
Btw. Sorry for obsoleting your PR, but without support for (aws-)chunked transfers (upload) it would still buffer all data before sending. Your PR did get me thinking, so it was not all in vain.

The current code tries to avoid data copying as much as possible. In the future I might add a bigstring version to truly support zero copy (That would change the internals to only use bigstrings, but memory pressure will suffer when using bigstrings, unless you call unsafe destroy (which is kind of and anti-pattern).

**Comment by andersfugmann** [comment]
Almost complete.
The API's have changed a bit, esp. the streaming get now takes a `string Pipe.writer`as argument:
```ocaml
module Stream : sig
  val get: 
    ?scheme:[ `Http | `Https ] ->
    ?credentials:Credentials.t ->
    ?region:Region.t ->
    ?range:range ->
    bucket:string ->
    key:string ->
    sink:string Pipe.writer ->
    unit -> (unit, error) Pervasives.result t
end 
``` 
How does that look. Esp. the name `sink` for the data return path seems imperfect, but I'm lacking a better name here. @hcarty Any suggestions?

**Comment by hcarty** [comment]
I think `sink` is ok, but if that's the name used in `get` then it may be nice from a consistency perspective to use `source` rather than `data` in `put`.

Maybe `data` would work in both `get` and `put` since it is the data pipe in both cases.  Only the direction of flow changes, and that's both implied in the function being called and explicit in the type.

Otherwise I think this interface looks good!  There are probably things that could be done with `bigstring`s or `bytes` to make avoid allocating new `string`s over and over again but I have no sense of how much that would matter in practice for this library.  And as I think you've said before, that could be added as a separate interface later on.

**Comment by andersfugmann** [comment]
Thanks for the input. 
I've changed the interface to use data for both put and get. 

- Its actually quite annoying that lwt's exception is so limited. I still believe that a better way would be to return Pipe.reader, but for lwt it makes the error handling somewhat tricky. With async the user would just install a monitor to retrieve any exceptions during the call, but lwt does not have this facility. 

But I can always add a new API, and deprecate the old one. 

As for the data copying, the only way to reduce data copying is to switch to bigstrings. 

The challenge with bigstrings is that the gc does not handle external memory pressure that well (yet - Improvements for this is scheduled for ocaml 4.08; https://github.com/ocaml/ocaml/pull/1738). This means that using bigstrings can in high memory pressure. I have no idea if this would actually be a problem in practice though. Using bigstrings would also make send more efficient as it allows using io-vectors. 

As you say, the Bigarray API can be added later. 
For now I would like to have the current changes released. There are plenty of changes. I will merge PR #8 now, and close this ticket once available in opam.

**Comment by andersfugmann** [comment]
https://github.com/ocaml/opam-repository/pull/12473

**Comment by andersfugmann** [comment]
Release is available through opam.
